### ISSUE TITLE
Consider WeakSet polyfill or falling back to Set

### ISSUE THREAD

**Issue by dparker2** [Andarist/stylis-plugin-extra-scope#6]
Hello! Thank you in advance for this tiny but very useful library.

I just spent the morning trying to make some new components usable in IE11, and this library turned out to cause issues because it uses `WeakSet` internally, which is not supported in IE11. This forces the consumer of this library to add a polyfill for it themself somehow before importing this library. It was not being automatically polyfilled in my case, because I have babel configured to only polyfill things that are used, and since babel does not transpile `node_modules`, it is not able to polyfill this.

Possible solutions:
- Something like what [React does](https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMEventHandle.js#L49) which is to check if `WeakSet` is defined, and if not fall back to `Set`.
- Setup babel to automatically polyfill it for you with [`"useBuiltIns": "usage"`](https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage)
- Add a disclaimer to the README saying that this library requires the consumer to polyfill `WeakSet` if it is intended to be used in IE11

**Comment by Andarist** [comment]
The only viable option here is the 3rd one. I dont think we can fallback to Set due to memory concerns. Importing a fallback is also not perfect because it would force everyone to pay that price - even if they dont care about IE11.

Would u like to prepare a docs PR for that?

**Comment by dparker2** [comment]
Yeah that all makes sense and sure, I can get a PR up for that addition tonight. Thanks for the quick response!

**Comment by Andarist** [comment]
Resolved by #7
