### ISSUE TITLE
License type?

### ISSUE THREAD

**Issue by ayastreb** [Andarist/stylis-plugin-extra-scope#8]
Hi!

What is the license for this project? package.json [says](https://github.com/Andarist/stylis-plugin-extra-scope/blob/master/package.json#L26) MIT, but there's no LICENSE file in the root.

Would you mind clarifying if this project is under MIT?

**Comment by Andarist** [comment]
Yes - it's MIT. I don't quite see why I need to provide the LICENSE file if the MIT text is the same for all projects if we are talking about pure MIT license. As you have mentioned - I already declare it in package.json, shouldn't this be enough?

**Comment by ayastreb** [comment]
Thanks for clarifying! [Adding a license](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository) file will just make it easier for people to see it :)
If you add a LICENSE file - GitHub will show a label on the project page and also in search results
